name: tekartik_travis_ci_flutter
description: Repo
version: 0.1.0
homepage: https://www.example.com
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dev_dependencies:
  process_run: '>=0.10.0'

dependency_overrides:
# tmp
#  process_run:
#    path: ../process_run.dart