name: tekartik_travis_ci_flutter
description: Travis CI flutter setup helper
version: 0.2.0
homepage: https://github.com/tekartik/travis_ci_flutter.dart
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.7.0-dev <3.0.0'

dependencies:
  meta: # dart.dev
  process_run: # 0.10.8 - TODO: secure code review 129f744d0b9b6e71cd78cd8207abda0e33c01570 (0.10.8)
    git:
      url: git://github.com/KomodoPlatform/process_run.dart.git
      ref: 129f744d0b9b6e71cd78cd8207abda0e33c01570

dev_dependencies:
  test: # dart.dev
  pedantic: # dart.dev
  path: # dart.dev

dependency_overrides:
# tmp
#  process_run:
#    path: ../process_run.dart
